package view;

public enum MainMenuAction {
    REGISTER,
    CREATE_TASK,
    DISPLAY_TASKS,
    CREATE_SQL_ITEM,
    CREATE_SQL_PERSON,
    FINDBYNAME_SQL,
    FINDBYID_SQL,

    FINDALL_SQL_PERSON,
    UPDATE_SQL,
    DELETE_SQL,
    CREATE_SQL_TODO,
    FINDALL_SQL_TODO,
    FINDBYID_SQL_TODO,
    FINDBYDONESTATUS_SQL_TODO,
    FINDBYASSIGNEE_INT_TODO,
    FINDBYASSIGNEE_PERSON_TODO,
    FINDBYUNASSIGNED_SQL_TODO,
    UPDATE_SQL_TODO,
    DELETEBYID_SQL_TODO,
    EXIT
}
